site_name: Mo Maher - Personal Blog
site_description: Personal blog of Mo Maher - Software Engineer and Tech Enthusiast
site_author: Mo Maher
site_url: https://blog.momaher.site

nav:
  - Home: index.md
  - Blog: blog/index.md
  - Portfolio: portfolio.md
  - Resume: resume.md
  - Achievements: achievements.md
  - Contact: contact.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
  icon:
    logo: material/rocket-launch
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: 'Poppins'
    code: 'Fira Code'
  language: en
  direction: ltr
  custom_dir: docs/overrides

plugins:
  - search
  - tags
  - blog
  - git-revision-date-localized:
      type: date
  - git-authors
  - glightbox
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/slorksmo
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/momaher94
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mo_maher94
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  comments:
    enabled: true
    provider: giscus
    repo: momaher/momaher.github.io
    repo_id: # Will be added after repository creation
    category: Announcements
    category_id: # Will be added after Giscus setup
    mapping: pathname
  social_share:
    enabled: true
    providers:
      - twitter
      - linkedin
      - facebook
      - email

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - footnotes
  - def_list
  - toc:
      permalink: true
