site_name: My Docs
theme:
  name: 'material'
  static_templates: []
  static_dir: 'overrides'
  include_search_page: false
  search_index_only: false
  palette:
    primary: 'indigo'
    accent: 'indigo'  # 'indigo'  # 'blue' 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange  
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'indigo'
      accent: 'indigo'
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'indigo'
      accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  icon:
    logo: null
    repo: null
  favicon: null
  logo: null
  feature:
    tabs: false
  language: 'en'
  direction: 'ltr'
