site_name: Mo Maher - Personal Blog
site_description: Personal blog of Mo Maher - Software Engineer and Tech Enthusiast
site_author: Mo Maher
site_url: https://momaher.github.io

nav:
  - Home: index.md
  - Blog: blog/index.md
  - Portfolio: portfolio.md
  - Resume: resume.md
  - Achievements: achievements.md
  - Contact: contact.md

theme:
  name: 'material'
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.language
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
  icon:
    logo: material/code-braces
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: 'Merriweather Sans'
    code: 'Red Hat Mono'
  language: 'en'
  direction: 'ltr'
  custom_dir: 'docs/overrides'

plugins:
  - search
  - tags
  - blog
  - git-revision-date-localized:
      type: date
  - rss

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/slorksmo
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/momaher94
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mo_maher94
  consent:
    title: Cookie consent
  comments:
    enabled: true
    provider: giscus
    repo: momaher/momaher.github.io
    repo_id: # سيتم إضافته لاحقاً بعد إنشاء المستودع
    category: Announcements
    category_id: # سيتم إضافته لاحقاً بعد إعداد Giscus
    mapping: pathname
  social_share:
    enabled: true
    providers:
      - twitter
      - linkedin
      - facebook
      - email

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - footnotes
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
